version: 0.1.0-pre{build}

pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
clone_depth: 1
install:
- cmd: git submodule update --init --recursive
build_script:
- ps: >-
    nuget restore source\nanoFramework.Tools.ANT.sln

    msbuild source\nanoFramework.Tools.ANT.sln /p:Configuration=Release  /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: '**\*
  name: UWP_App
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: nanoFramework Awesome Nano Tool v$(appveyor_build_version)
  description: add description here
  auth_token:
    secure: DNixoFFE+pGlwyhj7McfZoln42vOmj0iY1iNV9zXEr3y0NpXlOIgL8k5ehzlFM1S
  artifact: UWP_App
  draft: true
  prerelease: true
  force_update: true

# requires APPVEYOR_DISCORD_WEBHOOK_URL enviroment variable set with Discord webhook URL
on_failure:
  - ps: |

        cd ..

        .\appveyor-discord.ps1 failure $env:APPVEYOR_DISCORD_WEBHOOK_URL
